//! `vlpds.space.importRepo` (brief Q8, plan §2.7 "Migration in"): a space
//! repo exported with getRepo comes back in on another host, verified the
//! way `@atproto/space`'s `verifyRepoCarFull` verifies it, keeping its rev,
//! with an empty oplog, and served as it was.
//!
//! - From the reference: testdata/spaces-alpha/export.car, generated by
//!   running the reference's own serializer and signer at 5b95b2f2
//!   (gen-export.mjs), imported mid-migration.
//! - vlpds to vlpds: a member's repo moves between two vlpds hosts with the
//!   account, its blobs following through listMissingBlobs.
//! - Refusals: a tampered CAR, a bad signature or MAC, another DID's or
//!   another space's repo, over `--space-repo-max-records`, a space the
//!   account can't write in, and anything but OAuth. A refused import writes
//!   nothing.
//!
//! Mid-migration the account is deactivated on the new host (created with an
//! existing DID), and the commit still verifies under the old host's key,
//! the DID's current one. OAuth signs no deactivated account in, so the
//! import goes in on the createAccount session: the "narrow exception"
//! (option a) vlpds has today, while migration-in vs OAuth-only waits on a
//! decision. Space reads use an OAuth grant once the account is active.
//!
//! listMissingBlobs doesn't count imported space blob refs yet, so the
//! moves upload their space blobs without asking it
//! (`imported_space_blobs_are_listed_missing`, ignored, holds that contract).

use super::phase3::*;
use super::ref_net::*;
use crate::common::spaces::{Holder, SpaceClient};
use crate::common::*;
use crate::oauth;
use axum::extract::{Path, State};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::time::Duration;

const EXPORT_CAR: &[u8] = include_bytes!("../../../testdata/spaces-alpha/export.car");
const EXPORT_JSON: &str = include_str!("../../../testdata/spaces-alpha/export.json");

pub(super) type Docs = Arc<Mutex<HashMap<String, J>>>;

/// A PLC directory stand-in serving whatever documents a test puts in it
/// (tests/all/migration.rs's): a DID moves between hosts by a test
/// replacing its document.
pub(super) async fn stub_plc() -> (String, Docs) {
    let docs: Docs = Arc::default();
    let app = axum::Router::new()
        .route(
            "/{did}",
            axum::routing::get(|State(d): State<Docs>, Path(did): Path<String>| async move {
                match d.lock().unwrap().get(&did) {
                    Some(doc) => Ok(axum::Json(doc.clone())),
                    None => Err(axum::http::StatusCode::NOT_FOUND),
                }
            }),
        )
        .with_state(docs.clone());
    let l = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let url = format!("http://{}", l.local_addr().unwrap());
    tokio::spawn(async move { axum::serve(l, app).await.unwrap() });
    (url, docs)
}

/// A `--spaces` host on the stub directory.
pub(super) async fn stub_host(plc: &str, i: usize) -> TestServer {
    let plc = plc.to_string();
    TestServer::spawn_with(move |c| {
        c.plc_url = plc;
        c.service_did = format!("did:web:pds{i}.test");
        c.spaces = true;
    })
    .await
}

/// Puts `did`'s document, as `s` publishes it, in the directory.
pub(super) async fn publish(docs: &Docs, s: &TestServer, did: &str) {
    let doc = s.xrpc.get("com.atproto.identity.resolveDid", &[("did", did)], &Auth::None).await.ok()["didDoc"].clone();
    docs.lock().unwrap().insert(did.to_string(), doc);
}

/// A [`SpaceClient`] on `s` for an existing account (signed in with
/// `oauth::PASSWORD`), granted `scope`.
pub(super) async fn oauth_client(s: &TestServer, did: &str, handle: &str, jwt: &str, scope: &str) -> SpaceClient {
    let srv = oauth::Srv {
        app: s.app.clone(),
        base: s.url.clone(),
        http: reqwest::Client::builder().redirect(reqwest::redirect::Policy::none()).build().unwrap(),
    };
    let acct = oauth::Account { did: did.into(), handle: handle.into(), jwt: jwt.into() };
    let key = oauth::DpopKey::new();
    let scope = format!("atproto {scope}");
    let t = oauth::grant(&srv, &mut oauth::Browser::default(), &oauth::Flow::loopback(&scope, &key), &acct).await;
    SpaceClient {
        srv,
        did: did.into(),
        handle: handle.into(),
        session_jwt: jwt.into(),
        key,
        access: t.access,
        scope: t.scope,
        holder: Holder::new(),
    }
}

/// An account with an existing DID created on `new` (deactivated until the
/// DID moves), given the old host's service auth for it.
pub(super) struct Arrived {
    pub did: String,
    pub handle: String,
    /// The createAccount session: public methods, and importRepo while
    /// deactivated.
    pub session: Auth,
}

impl Arrived {
    /// The account's OAuth grant on `new`, once it's active there.
    pub async fn oauth(&self, new: &TestServer) -> SpaceClient {
        let Auth::Bearer(jwt) = &self.session else { unreachable!() };
        oauth_client(new, &self.did, &self.handle, jwt, FULL_SCOPE).await
    }

    pub async fn import(&self, new: &TestServer, space: &str, car: &[u8]) -> Resp {
        import_repo_as(&new.url, &self.session, space, car).await
    }
}

pub(super) async fn arrive(new: &TestServer, did: &str, service_auth: String) -> Arrived {
    let handle = format!("{}.{HANDLE_DOMAIN}", unique_name("moved"));
    let body = json!({"handle": handle, "email": format!("{}@example.com", unique_name("moved")), "password": oauth::PASSWORD, "did": did});
    let created = new.xrpc.post("com.atproto.server.createAccount", &body, &Auth::Bearer(service_auth)).await.ok();
    assert_eq!(created["did"], json!(did));
    let jwt = created["accessJwt"].as_str().unwrap().to_string();
    let st = new.xrpc.get("com.atproto.server.checkAccountStatus", &[], &Auth::Bearer(jwt.clone())).await.ok();
    assert_eq!(st["activated"], json!(false), "{st}");
    Arrived { did: did.into(), handle, session: Auth::Bearer(jwt) }
}

/// Points the DID at `new` with the key it recommends, and activates there.
pub(super) async fn complete_move(docs: &Docs, new: &TestServer, a: &Arrived) {
    let rec = new.xrpc.get("com.atproto.identity.getRecommendedDidCredentials", &[], &a.session).await.ok();
    let key = rec["verificationMethods"]["atproto"].as_str().unwrap();
    let doc = json!({
        "@context": ["https://www.w3.org/ns/did/v1"],
        "id": a.did,
        "alsoKnownAs": rec["alsoKnownAs"],
        "verificationMethod": [{
            "id": format!("{}#atproto", a.did), "type": "Multikey", "controller": a.did,
            "publicKeyMultibase": key.strip_prefix("did:key:").unwrap(),
        }],
        "service": [{"id": "#atproto_pds", "type": "AtprotoPersonalDataServer", "serviceEndpoint": new.url}],
    });
    docs.lock().unwrap().insert(a.did.clone(), doc);
    new.xrpc.post_empty("com.atproto.server.activateAccount", &a.session).await.ok();
}

async fn missing_blobs(s: &TestServer, auth: &Auth) -> Vec<String> {
    let r = s.xrpc.get("com.atproto.repo.listMissingBlobs", &[], auth).await.ok();
    r["blobs"].as_array().unwrap().iter().map(|b| b["cid"].as_str().unwrap().to_string()).collect()
}

/// check-space on the account's host checks the imported repo clean.
async fn check_space_ok(s: &TestServer, did: &str, space: &str) {
    let (r, out) = admin_cli(&s.url, &["--json", "check-space", did, space]).await;
    assert!(r.is_ok(), "check-space: {out}");
    let j: J = serde_json::from_str(&out).unwrap();
    assert_eq!(j["ok"], json!(true), "{j}");
}

/// The owner's view of its repo: getLatestCommit's (rev, hash).
async fn head(sc: &SpaceClient, space: &str) -> Option<(String, Vec<u8>)> {
    repo_state(sc, space).await
}

// ---------------------------------------------------------------------------
// the reference's export
// ---------------------------------------------------------------------------

struct Fixture {
    j: J,
    did: String,
    space: String,
    rev: String,
    key: vlpds::crypto::Keypair,
}

fn fixture() -> Fixture {
    let j: J = serde_json::from_str(EXPORT_JSON).unwrap();
    let key = vlpds::crypto::Keypair::from_bytes(&hex::decode(j["privateKeyHex"].as_str().unwrap()).unwrap()).unwrap();
    assert_eq!(key.did_key(), j["didKey"].as_str().unwrap(), "the fixture's key");
    Fixture {
        did: j["did"].as_str().unwrap().into(),
        space: j["space"].as_str().unwrap().into(),
        rev: j["rev"].as_str().unwrap().into(),
        key,
        j,
    }
}

/// The reference's CAR passes our port of verifyRepoCarFull, and the same
/// commit and records encode back to the same bytes: the reference and
/// vlpds agree on the export format (block order, index encoding, commit
/// encoding), which is what an import reads.
#[test]
fn reference_export_verifies_and_reencodes() {
    let f = fixture();
    let v = verify_repo_car(EXPORT_CAR, &f.space, &f.did, f.j["didKey"].as_str().unwrap(), true)
        .unwrap_or_else(|e| panic!("the reference's export doesn't verify: {e}"));
    assert_eq!(v.commit.rev, f.rev);
    assert_eq!(hex::encode(&v.commit.hash), f.j["hash"].as_str().unwrap());
    let want: Vec<(String, String)> = f.j["records"]
        .as_array()
        .unwrap()
        .iter()
        .map(|r| {
            (
                format!("{}/{}", r["collection"].as_str().unwrap(), r["rkey"].as_str().unwrap()),
                r["cid"].as_str().unwrap().to_string(),
            )
        })
        .collect();
    let mut sorted = want.clone();
    sorted.sort_by(|a, b| vlpds::cbor::key_cmp(&a.0, &b.0));
    let got: Vec<(String, String)> = v.index.iter().map(|(p, c)| (p.clone(), c.to_string())).collect();
    assert_eq!(got, sorted, "the index, in canonical (length-first) order");
    // the blob is named by a record, as a link
    let blob = f.j["blob"]["cid"].as_str().unwrap();
    assert!(v.records.iter().any(|(_, b)| Value::decode(b).unwrap().to_json().to_string().contains(blob)));

    let (roots, blocks) = vlpds::car::read_car(EXPORT_CAR).unwrap();
    assert_eq!(commit_block(&v.commit), blocks[0].1, "the commit block re-encodes byte for byte");
    assert_eq!(index_block(&v.index), blocks[1].1, "the index block re-encodes byte for byte");
    let owned: Vec<(Cid, Vec<u8>)> = blocks.iter().map(|(c, b)| (*c, b.to_vec())).collect();
    assert_eq!(write_car(&roots, &owned), EXPORT_CAR, "the CAR framing re-encodes byte for byte");

    // and a commit for another author or space, or a key that isn't the
    // DID's, is refused by the same checks
    let key = f.j["didKey"].as_str().unwrap();
    assert!(verify_repo_car(EXPORT_CAR, &f.space, "did:plc:someoneelse2345abcdefgh", key, true).is_err());
    assert!(verify_repo_car(EXPORT_CAR, &format!("{}x", f.space), &f.did, key, true).is_err());
    let other = vlpds::crypto::Keypair::generate().did_key();
    assert!(verify_repo_car(EXPORT_CAR, &f.space, &f.did, &other, true).is_err());
}

/// A reference-hosted account moves to vlpds with its space repo: created
/// with its DID (deactivated), the reference's getRepo CAR imported under
/// the DID's current key (the old host's), the record's blob listed missing
/// until uploaded, then the DID moves. vlpds then serves the same repo: the
/// same rev, set hash, index and record blocks, signed by its own key.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn reference_export_imports_mid_migration() {
    let f = fixture();
    let (plc, docs) = stub_plc().await;
    let new = stub_host(&plc, 1).await;
    let new_did = new.pds_did().await;
    // the DID's document on the reference host, before the move
    docs.lock().unwrap().insert(
        f.did.clone(),
        json!({
            "@context": ["https://www.w3.org/ns/did/v1"],
            "id": f.did,
            "alsoKnownAs": ["at://refexport.example"],
            "verificationMethod": [{
                "id": format!("{}#atproto", f.did), "type": "Multikey", "controller": f.did,
                "publicKeyMultibase": f.key.did_key().strip_prefix("did:key:").unwrap(),
            }],
            "service": [{"id": "#atproto_pds", "type": "AtprotoPersonalDataServer", "serviceEndpoint": "http://127.0.0.1:9"}],
        }),
    );
    let sa =
        vlpds::auth::service_auth_jwt(&f.key, &f.did, &new_did, Some("com.atproto.server.createAccount"), 60).unwrap();
    let a = arrive(&new, &f.did, sa).await;

    let out = a.import(&new, &f.space, EXPORT_CAR).await.ok();
    assert_eq!(out["rev"], json!(f.rev), "{out}");
    assert_eq!(out["records"], json!(5), "{out}");
    check_space_ok(&new, &f.did, &f.space).await;

    // the migration copies the record's blob
    let blob = f.j["blob"]["cid"].as_str().unwrap().to_string();
    let bytes = hex::decode(f.j["blob"]["bytesHex"].as_str().unwrap()).unwrap();
    let up = new.xrpc.post_bytes("com.atproto.repo.uploadBlob", bytes, "image/png", &a.session).await.ok();
    assert_eq!(up["blob"]["ref"]["$link"], json!(blob));
    assert!(missing_blobs(&new, &a.session).await.is_empty());

    complete_move(&docs, &new, &a).await;
    let oauth = a.oauth(&new).await;
    assert_eq!(head(&oauth, &f.space).await.map(|h| h.0), Some(f.rev.clone()));
    let (_, hash) = head(&oauth, &f.space).await.unwrap();
    assert_eq!(hex::encode(hash), f.j["hash"].as_str().unwrap());
    expect_set_hash_matches_store(&oauth, &f.space).await;
    let r = get_repo_self(&oauth, &f.space).await;
    assert_eq!(r.status, 200, "{}", r.text());
    let mine = verify_repo_car(&r.body, &f.space, &f.did, &did_key(&new, &f.did).await, true)
        .unwrap_or_else(|e| panic!("vlpds's getRepo after the import doesn't verify: {e}"));
    let theirs = verify_repo_car(EXPORT_CAR, &f.space, &f.did, &f.key.did_key(), true).unwrap();
    assert_eq!(
        (mine.commit.rev.clone(), mine.commit.hash.clone()),
        (theirs.commit.rev.clone(), theirs.commit.hash.clone())
    );
    assert_eq!(mine.index_cid, theirs.index_cid, "the same index block");
    assert_eq!(mine.records, theirs.records, "the same record blocks, in the same order");
    let b = dpop_raw(
        &oauth,
        &new.url,
        reqwest::Method::GET,
        "com.atproto.space.getBlob",
        &[("space", &f.space), ("repo", &f.did), ("cid", &blob)],
        None,
    )
    .await;
    assert_eq!((b.status, b.body.to_vec()), (200, hex::decode(f.j["blob"]["bytesHex"].as_str().unwrap()).unwrap()));

    // the oplog starts empty at the imported rev; the next write follows it
    let ops = oauth.get("com.atproto.space.listRepoOps", &[("space", &f.space), ("repo", &f.did)]).await.ok();
    assert_eq!(ops["ops"], json!([]), "{ops}");
    assert_eq!(ops["commit"]["rev"], json!(f.rev), "{ops}");
    let w = write(&oauth, &f.space, W::new().rkey("after-import").text("written on vlpds")).await.ok();
    let (rev, _) = head(&oauth, &f.space).await.unwrap();
    assert!(rev > f.rev, "a write after the import moves past its rev: {rev} vs {}", f.rev);
    assert!(w["uri"].as_str().unwrap().ends_with("/after-import"), "{w}");
    let ops = oauth
        .get("com.atproto.space.listRepoOps", &[("space", &f.space), ("repo", &f.did), ("since", &f.rev)])
        .await
        .ok();
    let mut set = LtHash::default();
    for (p, c) in theirs.set() {
        let (coll, rkey) = p.split_once('/').unwrap();
        set.add(&vlpds::space::commit::element(coll, rkey, &c));
    }
    for op in ops["ops"].as_array().unwrap() {
        super::fuzz::fold(&mut set, op);
    }
    assert!(commit_matches(&set, &ops["commit"]), "the imported set plus the new ops is the head");
    check_space_ok(&new, &f.did, &f.space).await;
}

use vlpds::space::lthash::LtHash;

/// The reference export's record names a blob the new host doesn't hold
/// yet: listMissingBlobs lists it until the migration uploads it.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
#[ignore = "not built: listMissingBlobs counts public blob refs only, not imported space ones (sb/)"]
async fn imported_space_blobs_are_listed_missing() {
    let f = fixture();
    let (plc, docs) = stub_plc().await;
    let new = stub_host(&plc, 1).await;
    let new_did = new.pds_did().await;
    docs.lock().unwrap().insert(
        f.did.clone(),
        json!({
            "@context": ["https://www.w3.org/ns/did/v1"],
            "id": f.did,
            "verificationMethod": [{
                "id": format!("{}#atproto", f.did), "type": "Multikey", "controller": f.did,
                "publicKeyMultibase": f.key.did_key().strip_prefix("did:key:").unwrap(),
            }],
            "service": [{"id": "#atproto_pds", "type": "AtprotoPersonalDataServer", "serviceEndpoint": "http://127.0.0.1:9"}],
        }),
    );
    let sa =
        vlpds::auth::service_auth_jwt(&f.key, &f.did, &new_did, Some("com.atproto.server.createAccount"), 60).unwrap();
    let a = arrive(&new, &f.did, sa).await;
    a.import(&new, &f.space, EXPORT_CAR).await.ok();
    let blob = f.j["blob"]["cid"].as_str().unwrap().to_string();
    assert_eq!(missing_blobs(&new, &a.session).await, vec![blob]);
}

// ---------------------------------------------------------------------------
// vlpds to vlpds
// ---------------------------------------------------------------------------

/// Two hosts on the stub directory, bob moving from the first to the
/// second; alice governs a space on a third, bob (a member, on the first)
/// writes into it, carol (on the first) reads. The authority isn't on bob's
/// old host: these hosts run with unregistered DIDs, so that host would
/// keep verifying bob by its own document after he left, where a directory
/// host resolves the moved DID.
pub(super) struct TwoHosts {
    pub docs: Docs,
    pub a: TestServer,
    pub b: TestServer,
    /// alice's host.
    pub c: TestServer,
    pub alice: SpaceClient,
    pub bob: SpaceClient,
    pub carol: SpaceClient,
    pub space: String,
}

pub(super) async fn two_hosts() -> TwoHosts {
    let (plc, docs) = stub_plc().await;
    let (a, b, c) = (stub_host(&plc, 0).await, stub_host(&plc, 1).await, stub_host(&plc, 2).await);
    let mut who = Vec::new();
    for (name, host) in [("alice", &c), ("bob", &a), ("carol", &a)] {
        let sc = SpaceClient::new(host, &unique_name(name), FULL_SCOPE).await;
        publish(&docs, host, &sc.did).await;
        who.push(sc);
    }
    let carol = who.pop().unwrap();
    let bob = who.pop().unwrap();
    let alice = who.pop().unwrap();
    let space = format!("at://{}/space/{TEST_SPACE_TYPE}/{}", alice.did, unique_name("mv"));
    let skey = last_segment(&space).to_string();
    let r = alice
        .post(
            "com.atproto.simplespace.createSpace",
            json!({"spaceType": TEST_SPACE_TYPE, "skey": skey, "readPolicy": member_list(), "writePolicy": member_list(), "appAccess": open()}),
        )
        .await;
    assert_eq!(r.ok()["uri"], json!(space));
    for m in [&bob, &carol] {
        put_member(&alice, &space, m, true, true).await.ok();
    }
    TwoHosts { docs, a, b, c, alice, bob, carol, space }
}

/// bob's writes: creates, an update, a delete and a record naming a blob.
/// Returns the blob's CID and bytes.
pub(super) async fn fill_bob(h: &TwoHosts) -> (String, Vec<u8>) {
    for i in 0..6 {
        write(&h.bob, &h.space, W::new().rkey(&format!("r{i}")).text(&format!("bob {i}"))).await.ok();
    }
    put(&h.bob, &h.space, W::new().rkey("r1").text("bob 1, revised")).await.ok();
    del(&h.bob, &h.space, None, "r2").await.ok();
    let bytes = format!("\u{89}PNG\r\n\x1a\n bob's space image {}", unique_name("img")).into_bytes();
    let blob = upload_blob(&h.bob, &bytes).await;
    let rec = json!({"$type": TEST_COLLECTION, "text": "with an image", "image": blob});
    write(&h.bob, &h.space, W::new().rkey("img").record(rec)).await.ok();
    (blob_cid(&blob), bytes)
}

/// bob, on host b with a deactivated account and his space repo imported
/// (blobs copied): the move up to the DID switch, then the switch, so his
/// OAuth grant there (the second value) reads the repo.
pub(super) async fn move_bob(h: &TwoHosts, blob: &(String, Vec<u8>)) -> (SpaceClient, VerifiedRepo) {
    let b_did = h.b.pds_did().await;
    let sa = service_jwt(&h.bob, &b_did, "com.atproto.server.createAccount").await;
    let arrived = arrive(&h.b, &h.bob.did, sa).await;
    let r = get_repo_self(&h.bob, &h.space).await;
    assert_eq!(r.status, 200, "{}", r.text());
    let exported = verify_repo_car(&r.body, &h.space, &h.bob.did, &did_key(&h.a, &h.bob.did).await, true).unwrap();
    let out = arrived.import(&h.b, &h.space, &r.body).await.ok();
    assert_eq!(out["rev"], json!(exported.commit.rev), "{out}");
    assert_eq!(out["records"], json!(exported.index.len()), "{out}");
    // the blob from the old host's space.getBlob, as the migrate page copies it
    let (status, _, got) = h
        .bob
        .get_raw("com.atproto.space.getBlob", &[("space", &h.space), ("repo", &h.bob.did), ("cid", &blob.0)])
        .await;
    assert_eq!((status, &got), (200, &blob.1));
    h.b.xrpc.post_bytes("com.atproto.repo.uploadBlob", got, "image/png", &arrived.session).await.ok();
    assert!(missing_blobs(&h.b, &arrived.session).await.is_empty());
    complete_move(&h.docs, &h.b, &arrived).await;
    (arrived.oauth(&h.b).await, exported)
}

/// bob's space repo moves from one vlpds host to another with his account:
/// the head (rev and hash), the records, the blob refs and an empty oplog
/// at the imported rev; check-space passes; carol's credential reads the
/// same records from the new host; the authority hears the new host's
/// writes.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn vlpds_export_imports_on_another_vlpds() {
    let h = two_hosts().await;
    let blob = fill_bob(&h).await;
    let before = head(&h.bob, &h.space).await.unwrap();
    let cred_a = h.carol_cred().await;
    let records_a = listed(&h.a.url, &cred_a, &h.space, &h.bob.did).await;
    assert_eq!(records_a.len(), 6);

    let (moved, exported) = move_bob(&h, &blob).await;
    let moved = &moved;
    assert_eq!(head(moved, &h.space).await, Some(before.clone()), "the head moves as it was");
    expect_set_hash_matches_store(moved, &h.space).await;
    check_space_ok(&h.b, &h.bob.did, &h.space).await;
    let ops = moved.get("com.atproto.space.listRepoOps", &[("space", &h.space), ("repo", &h.bob.did)]).await.ok();
    assert_eq!(ops["ops"], json!([]), "the oplog starts empty: {ops}");
    assert_eq!(ops["commit"]["rev"], json!(before.0));
    let lb = moved.get("com.atproto.space.listBlobs", &[("space", &h.space), ("repo", &h.bob.did)]).await.ok();
    assert_eq!(lb["cids"], json!([blob.0]), "{lb}");

    h.a.xrpc
        .post("com.atproto.server.deactivateAccount", &json!({}), &Auth::Bearer(h.bob.session_jwt.clone()))
        .await
        .ok();
    let r = get_repo_self(moved, &h.space).await;
    let served = verify_repo_car(&r.body, &h.space, &h.bob.did, &did_key(&h.b, &h.bob.did).await, true)
        .unwrap_or_else(|e| panic!("the new host's getRepo doesn't verify: {e}"));
    assert_eq!(served.index, exported.index);
    assert_eq!(served.records, exported.records);
    assert_eq!((served.commit.rev, served.commit.hash), (exported.commit.rev.clone(), exported.commit.hash.clone()));

    // carol's credential (from the authority on c) reads bob at b
    let cred = h.carol_cred().await;
    assert_eq!(listed(&h.b.url, &cred, &h.space, &h.bob.did).await, records_a);
    let latest =
        cred.get(&h.b.url, "com.atproto.space.getLatestCommit", &[("space", &h.space), ("repo", &h.bob.did)]).await;
    assert_eq!(latest.ok()["commit"]["rev"], json!(before.0));

    // bob writes on b: the authority on c hears the newer rev
    write(moved, &h.space, W::new().rkey("on-b").text("from the new host")).await.ok();
    let (rev, _) = head(moved, &h.space).await.unwrap();
    let mut seen = J::Null;
    for _ in 0..100 {
        seen = cred.get(&h.c.url, "com.atproto.space.listRepos", &[("space", &h.space)]).await.ok();
        let bob = seen["repos"].as_array().unwrap().iter().find(|x| x["did"] == json!(h.bob.did));
        if bob.is_some_and(|b| b["repoRev"] == json!(rev)) {
            break;
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
    let bob = seen["repos"].as_array().unwrap().iter().find(|x| x["did"] == json!(h.bob.did));
    assert_eq!(
        bob.map(|b| &b["repoRev"]),
        Some(&json!(rev)),
        "the authority's listRepos after bob wrote on the new host: {seen}"
    );
    let mut s = Syncer::new(&h.b.url, &h.space, &h.bob.did, &did_key(&h.b, &h.bob.did).await, cred);
    s.full().await;
    let now = listed(&h.b.url, &h.carol_cred().await, &h.space, &h.bob.did).await;
    assert_eq!(now.len(), records_a.len() + 1);
    assert!(records_a.iter().all(|(p, c)| now.get(p) == Some(c)), "{now:?}");
    assert_eq!(s.set, now);
}

impl TwoHosts {
    pub(super) async fn carol_cred(&self) -> Cred {
        let token = delegation_token(&self.carol, &self.space).await;
        let holder = Holder::new();
        let r = exchange(&reqwest::Client::new(), &holder, &self.c.url, &self.space, &token, None).await;
        Cred { credential: r.ok()["credential"].as_str().unwrap().to_string(), holder, http: reqwest::Client::new() }
    }
}

// ---------------------------------------------------------------------------
// imports on one host, and refusals
// ---------------------------------------------------------------------------

/// alice governs a space on one host; bob may write in it.
struct One {
    net: Net,
    alice: SpaceClient,
    bob: SpaceClient,
    space: String,
}

async fn one() -> One {
    let net = Net::new(0).await;
    let (alice, bob) = (net.actor("alice", 0).await, net.actor("bob", 0).await);
    let space = net.create_space(&alice, SpaceOpts { members: &[&bob], ..Default::default() }).await;
    One { net, alice, bob, space }
}

fn records(b: RepoBuilder, n: usize) -> RepoBuilder {
    (0..n).fold(b, |b, i| {
        b.record(TEST_COLLECTION, &format!("imp{i:04}"), record(TEST_COLLECTION, &format!("imported {i}")))
    })
}

async fn nothing_written(sc: &SpaceClient, space: &str, what: &str) {
    assert_eq!(head(sc, space).await, None, "{what}: a refused import wrote a repo");
}

/// A repo bob never wrote here, signed with his own key (a restore from
/// his backup): imported at its rev, served, then written on; the authority
/// sequences it.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn imports_a_restored_repo_and_takes_writes_after() {
    let o = one().await;
    let s = &o.net.pds[0];
    let rev = rev_ago(Duration::from_secs(3600));
    let b = records(RepoBuilder::new(&o.space, &o.bob.did, &rev), 7);
    let built = b.build(&*account_key(s, &o.bob.did).await);
    let out = import_repo(&o.bob, &o.space, &built.car()).await.ok();
    assert_eq!((out["rev"].clone(), out["records"].clone()), (json!(rev), json!(7)), "{out}");
    assert_eq!(head(&o.bob, &o.space).await, Some((rev.clone(), b.set().digest().to_vec())));
    check_space_ok(s, &o.bob.did, &o.space).await;
    let writers = o.net.await_writer(&o.alice, &o.space, &o.bob.did).await;
    assert!(writers.contains(&o.bob.did), "the authority sequences the imported repo: {writers:?}");

    let cred = o.net.credential_for(&o.alice, &o.space).await;
    let got = listed(&s.url, &cred, &o.space, &o.bob.did).await;
    let want: std::collections::BTreeMap<String, String> =
        built.records.iter().map(|(p, c, _)| (p.clone(), c.to_string())).collect();
    assert_eq!(got, want);
    write(&o.bob, &o.space, W::new().rkey("later").text("after the restore")).await.ok();
    let (after, _) = head(&o.bob, &o.space).await.unwrap();
    assert!(after > rev);
    expect_set_hash_matches_store(&o.bob, &o.space).await;
}

/// The reference's verifyRepoCarFull refuses each of these, and so does
/// the import, writing nothing: a record block whose bytes don't hash to
/// its CID, an index entry naming another CID, a missing record block, an
/// extra block, blocks out of index order, the index before the commit.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn refuses_a_tampered_car() {
    let o = one().await;
    let s = &o.net.pds[0];
    let key = account_key(s, &o.bob.did).await;
    let dk = key.did_key();
    let b = records(RepoBuilder::new(&o.space, &o.bob.did, &rev_ago(Duration::from_secs(60))), 4);
    let built = b.build(&key);
    assert!(verify_repo_car(&built.car(), &o.space, &o.bob.did, &dk, true).is_ok());

    let mut cases: Vec<(&str, Vec<u8>)> = vec![
        (
            "a record's bytes changed",
            built.car_with(|bl| bl[3].1 = record_block(&record(TEST_COLLECTION, "tampered")).1),
        ),
        ("a record block missing", built.car_with(|bl| drop(bl.remove(4)))),
        ("an extra block", built.car_with(|bl| bl.push(record_block(&record(TEST_COLLECTION, "extra"))))),
        ("records out of index order", built.car_with(|bl| bl.swap(2, 3))),
        ("the index before the commit", built.car_with(|bl| bl.swap(0, 1))),
    ];
    // an index entry swapped for another record's CID: still a valid block,
    // but it no longer folds to the signed hash
    let mut swapped = built.records.iter().map(|(p, c, _)| (p.clone(), *c)).collect::<Vec<_>>();
    swapped[0].1 = record_block(&record(TEST_COLLECTION, "another")).0;
    let ib = index_block(&swapped);
    let icid = Cid::dag_cbor(&ib);
    let mut blocks = vec![(built.commit_cid, built.commit_block.clone()), (icid, ib)];
    blocks.extend(built.records.iter().map(|(_, c, b)| (*c, b.clone())));
    cases.push(("an index entry naming another CID", write_car(&[built.commit_cid, icid], &blocks)));
    cases.push(("not a CAR", b"not a car at all".to_vec()));
    cases.push(("one root", {
        let all = built.car_with(|_| {});
        let (_, bl) = vlpds::car::read_car(&all).unwrap();
        let owned: Vec<(Cid, Vec<u8>)> = bl.iter().map(|(c, b)| (*c, b.to_vec())).collect();
        write_car(&[built.commit_cid], &owned)
    }));

    for (what, car) in &cases {
        assert!(
            verify_repo_car(car, &o.space, &o.bob.did, &dk, true).is_err(),
            "{what}: the reference would accept it"
        );
        let r = import_repo(&o.bob, &o.space, car).await;
        assert_eq!(r.status, 400, "{what}: {}", r.text());
        nothing_written(&o.bob, &o.space, what).await;
    }
    import_repo(&o.bob, &o.space, &built.car()).await.ok();
}

/// A commit signed by a key that isn't the DID's, a MAC that doesn't bind
/// the hash, and a hash the records don't fold to are refused.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn refuses_a_bad_signature_or_mac() {
    let o = one().await;
    let s = &o.net.pds[0];
    let key = account_key(s, &o.bob.did).await;
    let b = records(RepoBuilder::new(&o.space, &o.bob.did, &rev_ago(Duration::from_secs(60))), 3);

    let wrong_key = b.build(&vlpds::crypto::Keypair::generate());
    let mut bad_mac = b.build(&key);
    bad_mac.commit.mac[0] ^= 1;
    bad_mac.commit_block = commit_block(&bad_mac.commit);
    bad_mac.commit_cid = Cid::dag_cbor(&bad_mac.commit_block);
    // the MAC rebound to another hash, as anyone holding a commit can: the
    // signature and MAC verify, the index doesn't fold to it
    let mut rebound = b.build(&key);
    let mut other = b.set();
    other.add("com.example.x/y/bafyreie5737gdxlw5i64vzichcalba3z2v5n6icifvx5xytvske7mr3hpm");
    let ctx = vlpds::space::commit::encode_ctx(
        &vlpds::space::commit::CommitCtx { space: &o.space, author: &o.bob.did, rev: &rebound.commit.rev },
        &rebound.commit.ikm,
    )
    .unwrap();
    rebound.commit.hash = other.digest().to_vec();
    rebound.commit.mac = vlpds::space::commit::mac(&rebound.commit.ikm, &ctx, &rebound.commit.hash).to_vec();
    rebound.commit_block = commit_block(&rebound.commit);
    rebound.commit_cid = Cid::dag_cbor(&rebound.commit_block);

    let dk = key.did_key();
    for (what, built) in
        [("another key's signature", wrong_key), ("a broken MAC", bad_mac), ("a rebound hash", rebound)]
    {
        let car = built.car();
        assert!(verify_repo_car(&car, &o.space, &o.bob.did, &dk, true).is_err(), "{what}");
        let r = import_repo(&o.bob, &o.space, &car).await;
        assert_eq!(r.status, 400, "{what}: {}", r.text());
        nothing_written(&o.bob, &o.space, what).await;
    }
}

/// alice's repo (signed by alice for this space) imported by bob, bob's
/// repo for another space imported into this one, and a CAR whose commit
/// names another space are refused.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn refuses_another_dids_or_another_spaces_repo() {
    let o = one().await;
    let s = &o.net.pds[0];
    let rev = rev_ago(Duration::from_secs(60));
    let alices = records(RepoBuilder::new(&o.space, &o.alice.did, &rev), 2).build(&*account_key(s, &o.alice.did).await);
    let r = import_repo(&o.bob, &o.space, &alices.car()).await;
    assert_eq!(r.status, 400, "another DID's repo: {}", r.text());
    nothing_written(&o.bob, &o.space, "another DID's repo").await;

    let other = o.net.create_space(&o.alice, SpaceOpts { members: &[&o.bob], ..Default::default() }).await;
    let for_other = records(RepoBuilder::new(&other, &o.bob.did, &rev), 2).build(&*account_key(s, &o.bob.did).await);
    let r = import_repo(&o.bob, &o.space, &for_other.car()).await;
    assert_eq!(r.status, 400, "another space's repo: {}", r.text());
    nothing_written(&o.bob, &o.space, "another space's repo").await;
    // where it belongs, it imports
    import_repo(&o.bob, &other, &for_other.car()).await.ok();
}

/// `--space-repo-max-records` (100k) bounds an import as it bounds writes.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn refuses_a_repo_over_the_record_cap() {
    let o = one().await;
    let s = &o.net.pds[0];
    let key = account_key(s, &o.bob.did).await;
    let rev = rev_ago(Duration::from_secs(60));
    let mut b = RepoBuilder::new(&o.space, &o.bob.did, &rev);
    for i in 0..100_001u32 {
        b.records
            .insert(format!("{TEST_COLLECTION}/c{i:06}"), record_block(&json!({"$type": TEST_COLLECTION, "i": i})));
    }
    let car = b.build(&key).car();
    let r = import_repo(&o.bob, &o.space, &car).await;
    refused_mentioning(&r, &["limit", "max"]);
    nothing_written(&o.bob, &o.space, "over the cap").await;
    // at the cap it goes in
    b.records.pop_last();
    import_repo(&o.bob, &o.space, &b.build(&key).car()).await.ok();
}

/// Importing a repo is writing it: an account that isn't a member of the
/// space, or is one without write, is refused as its writes would be, and
/// accepted once the authority lets it write.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn refuses_a_space_the_account_cant_write_in() {
    let net = Net::new(0).await;
    let (alice, carol) = (net.actor("alice", 0).await, net.actor("carol", 0).await);
    let space = net.create_space(&alice, SpaceOpts::default()).await;
    let s = &net.pds[0];
    let built = records(RepoBuilder::new(&space, &carol.did, &rev_ago(Duration::from_secs(60))), 2)
        .build(&*account_key(s, &carol.did).await);
    let r = import_repo(&carol, &space, &built.car()).await;
    refused_mentioning(&r, &["member", "not authorized", "forbidden", "write"]);
    nothing_written(&carol, &space, "not a member").await;
    put_member(&alice, &space, &carol, true, false).await.ok();
    let r = import_repo(&carol, &space, &built.car()).await;
    refused_mentioning(&r, &["member", "not authorized", "forbidden", "write"]);
    nothing_written(&carol, &space, "a member without write").await;
    put_member(&alice, &space, &carol, true, true).await.ok();
    import_repo(&carol, &space, &built.car()).await.ok();
}

/// Space data is OAuth-only (brief, FINAL): a password session and app
/// passwords are refused, and an OAuth grant must allow writing in the
/// space.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn import_is_oauth_only() {
    let o = one().await;
    let s = &o.net.pds[0];
    let built = records(RepoBuilder::new(&o.space, &o.bob.did, &rev_ago(Duration::from_secs(60))), 2)
        .build(&*account_key(s, &o.bob.did).await);
    let car = built.car();
    let session = Auth::Bearer(o.bob.session_jwt.clone());
    let mut auths = vec![("password session", session.clone())];
    for privileged in [false, true] {
        let ap = s
            .xrpc
            .post(
                "com.atproto.server.createAppPassword",
                &json!({"name": format!("imp-{privileged}"), "privileged": privileged}),
                &session,
            )
            .await
            .ok();
        let sess = s.create_session(&o.bob.did, ap["password"].as_str().unwrap()).await.ok();
        auths.push(("app password", Auth::Bearer(sess["accessJwt"].as_str().unwrap().into())));
    }
    auths.push(("no auth", Auth::None));
    for (what, auth) in &auths {
        let r = import_repo_as(&s.url, auth, &o.space, &car).await;
        assert!(r.status == 401 || r.status == 403, "{what}: {}", r.text());
        nothing_written(&o.bob, &o.space, what).await;
    }
    let read_only = regrant(&o.bob, &format!("space:{TEST_SPACE_TYPE}?authority=*&collection=*&action=read")).await;
    let r = import_repo(&read_only, &o.space, &car).await;
    assert!((400..500).contains(&r.status), "a read-only grant: {}", r.text());
    nothing_written(&o.bob, &o.space, "a read-only grant").await;
    import_repo(&o.bob, &o.space, &car).await.ok();
}
